// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "68qiO74NqyH0caaUyINfQ9KHvO0sV0A5laRAc38y22KejcMRL9AXL4HNSkpVLsnckyb3o0";
}
}
}

